---
- name: "Clear Nodesource"
  shell: "rm -rf /etc/apt/sources.list.d/nodesource.list"

- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "Install Python"
  apt:
    name:
      - "python3-pip"
      - "python3-venv"

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: 
      - nodejs
      - npm
    state: present

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: Creates directory
  file:
    path: ~/web
    state: directory
