---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
  
- name: "resolve dependency issues"
  become: yes
  shell: "apt-get install libssl1.0.0=1.0.2g-1ubuntu4.1"

- name: "Install NodeJs and NPM"
  become: yes
  apt:
    name:
      - "nodejs"
      - "npm"
    update_cache: yes
  
- name: "Install pm2"
  npm:
    name: "pm2"
    global: "yes"
    state: latest

- name: "Install Python"
  apt:
    name:
      - "python3-pip"
      - "python3-venv"

- name: "Creates directory"
  file:
    path: ~/web
    state: directory